### ISSUE TITLE
Wierd problem with " ' " in f-strings...

### ISSUE THREAD

**Issue by cpierquet** [tndrle/PyLuaTeX#18]
Hi-

I've got a wierd problem, with `pyluatex` and `piton`.
In some f-strings, the character `'` give me problems, like in the following MWE :

```
\documentclass[a4paper,11pt]{article}
\usepackage{xparse}
\usepackage{xcolor}
\usepackage{piton}
\usepackage[executable=python]{pyluatex}
\NewDocumentEnvironment{PitonREPL}{ !O{} } %given by pton's doc
{
	\PitonOptions{background-color=white,prompt-background-color=white,#1}
	\PyLTVerbatimEnv
	\begin{pythonrepl}
}
{
	\directlua{
		tex.print("\\begin{Piton}")
		tex.print(pyluatex.get_last_output())
		tex.print("\\end{Piton}")
		tex.print("")
	}
	\end{pythonrepl}
}

\begin{document}

\begin{pythonq}
x = "Hello PyLuaTeX, it's cool !"

def test(n):
	if n%2 == 0 :
		print(f"{n} is odd.")
	else :
		#not working : print(f"{n} isn't odd.")
		print(f"{n} isnʼt odd.")  #working, but no '
	
\end{pythonq}

\begin{PitonREPL}
x
\end{PitonREPL}

\begin{PitonREPL}
test(12)
\end{PitonREPL}

\begin{PitonREPL}
test(13)
\end{PitonREPL}

\end{document}
```
![sx-2023-01-30-133353-CUserscpierquetOneDriveProjetsA_TESTER_LATEXateste](https://user-images.githubusercontent.com/45103962/215478332-fc4856cf-bacb-416d-bbb7-1aa924082819.png)

**Comment by tndrle** [comment]
Hi,

there are two different problems, I think.

### Why is the `ʼ` not shown?
The font doesn't have that character. The log says `Missing character: There is no ʼ (U+02BC) in font [lmmono10-regular]`. A different font should solve this.

### Why is `print(f"{n} isn't odd.")` (with the normal _tick_) not working?
First, to make sure we talk about the same thing, I get the following error when I uncomment the respective `print`:
```
attempt to index a nil value
stack traceback:
	[C]: in for iterator 'for iterator'
	[\directlua]:505: in field 'Parse'
	[\directlua]:590: in field 'GobbleParse'
	[\directlua]:1: in main chunk.
\__piton_collect_Piton:w ....scan_argument())}{#1}
                                                  \vspace {2.5pt}\egroup \bo...

l.47 \end{PitonREPL}
```

I played around a bit and came up with this:
```
\documentclass[a4paper,11pt]{article}
\usepackage{xparse}
\usepackage{xcolor}
\usepackage{piton}
\usepackage[executable=python]{pyluatex}
\NewDocumentEnvironment{PitonREPL}{ !O{} } %given by pton's doc
{
	\PitonOptions{background-color=white,prompt-background-color=white,#1}
	\PyLTVerbatimEnv
	\begin{pythonrepl}
}
{
	\directlua{
		tex.print("\\begin{Piton}")
		tex.print(pyluatex.get_last_output())
		tex.print("\\end{Piton}")
		tex.print("")
	}
	\end{pythonrepl}
}

\begin{document}

\begin{pythonq}
x = "Hello PyLuaTeX, it's cool !"
\end{pythonq}

\begin{python}
print("'")
\end{python}

\begin{python}
print(f"'")
\end{python}

\begin{PitonREPL}
x
\end{PitonREPL}

\begin{PitonREPL}
print(x)
\end{PitonREPL}

\end{document}
```

The two `python` environments work fine. Both write the tick to the PDF.
__Therefore, I don't think the f-string is the problem.__

The first `PitonREPL` environment works fine as well. The PDF contains
```
>>> x
"Hello PyLuaTeX, it's cool !"
```
with the desired highlighting. The text is red because it is a string.

Finally, an error is thrown at the last `PitonREPL` environment.
The expected output would be
```
>>> print(x)
Hello PyLuaTeX, it's cool !
```
This time, the text is (expected to be???) black (you can see that if you remove the `'`, then it compiles).
__Therefore, I think the problem is somewhere in the syntax highlighting code of Piton.__

**Comment by tndrle** [comment]
This confirms my conclusion, I guess:
```
\documentclass[a4paper,11pt]{article}
\usepackage{xcolor}
\usepackage{piton}

\begin{document}
\begin{Piton}
"Hello PyLuaTeX, it's cool !"
\end{Piton}

\begin{Piton}
Hello PyLuaTeX, it's cool !
\end{Piton}
\end{document}
```

The second `Piton` environment fails. Probably because it isn't valid Python code, so no proper syntax highlighting can be done.
