### ISSUE TITLE
python environment inside an other one

### ISSUE THREAD

**Issue by jowe19** [tndrle/PyLuaTeX#2]
I tried to define other environments using the `python` and `pythonq` environments, but the simple example below (`codepyexec`) does not work. How can I fix it ?

```
\newenvironment{codepyexec}
	{\VerbatimEnvironment\begin{python}}
	{\end{python}}
```

**Comment by tndrle** [comment]
Hi, I don't think this is possible (if I get your intention right).

When you use
```latex
\begin{codepyexec}
...
\end{codepyexec}
```
`\begin{codepyexec}` calls `\begin{python}` and the `python` environment is started as expected. However, the `python` environment will never be ended properly and that is the problem.

Once the `python` environment is started with `\begin{python}`, everything that follows is treated as Python code and only `\end{python}` can end the `python` environment. Unfortunately, `\end{python}` will never be called in your approach because `\end{codepyexec}` (which you would expect to call `\end{python}`) is consumed by the `python` environment and treated as Python code. It's never expanded by LaTeX and therefore `\end{python}` is never called. That's the usual behavior for verbatim environments in LaTeX. I don't think there is much you can do about it. Maybe some hacks but I don't know any.

**Comment by jowe19** [comment]
Thank you for your answer. 

To do the same kind of trick with `pythontex` I was placing the `\VerbatimEnvironment` command at the beginning of the new environment and it works well, but this does not work with `pyluatex` unfortunately.

**Comment by tndrle** [comment]
Hey, thanks for the additional details. I didn't know it could be done so easily.

`\VerbatimEnvironment` does not work because the way I read verbatim content is very different than in the `pythontex` package. I use a Lua-based approach following [1]. Because of this, if you start a `python` environment, really everything until `\end{python}` is consumed. This is hard-coded (more or less). No real way to change it from the document, at least in the current version of PyLuaTeX.

However, I find your approach of creating new environments very nice and I already have some ideas how PyLuaTeX could be adapted to provide such functionality. I have to think about it a little more, though. Maybe I can add it in the next release.

[1] Isambert, P. (2011). LuaTEX: What it takes to make a paragraph. TUGboat-TeX Users Group, 32(1), 68. https://tug.org/TUGboat/tb32-1/tb100isambert.pdf

**Comment by tndrle** [comment]
I added a macro named `\PyLTVerbatimEnv` in the experimental branch `verbatim-env`.

This allows for example the following
```latex
\documentclass{article}

\usepackage{pyluatex}

\newenvironment{codepyexec}
{\PyLTVerbatimEnv Something before \begin{python}}
{\end{python} Something after}

\begin{document}

\begin{codepyexec}
print('A')
\end{codepyexec}

\end{document}
```

Feel free to check it out and test it with your use cases.

**Comment by jowe19** [comment]
Thanks for your message and this new command, I'm going to test. Just an off-topic question: is there a simple way to install this `Pyluatex` version (of the branch `verbatim-env`) in TexLive? Do I have to uninstall the old one?

**Comment by tndrle** [comment]
Hey,

you'll have to uninstall the current version (`tlmgr remove pyluatex`; maybe with `sudo`).
After that, simply clone the repo to your local TEXMF folder under `TEXMF/tex/latex/pyluatex` and check out the new branch. The location of the TEXMF folder may vary. Typical defaults for TeX Live are `~/texmf` for Linux, `~/Library/texmf` for macOS, and `C:\Users\<user name>\texmf` for Windows. If it doesn't exist yet, you have to create it. Also see https://github.com/tndrle/PyLuaTeX#installation

Let me know if there are problems. I appreciate your feedback.

**Comment by jowe19** [comment]
Thanks ! I just had to use the `--force` option of `tlmgr remove` in order to ignore a dependency. 

I have created some environments for me, using the `pyluatex` environments and mainly `tcolorbox` (with the `minted` library` in order to print code without execution), and so far everything works fine. 

I was also wondering if it was possible to have an environment mimicking the python console ? (like the `pyconsole` environment of `Pythontex`, see the picture for an example). 
<img width="194" alt="Capture d’écran 2021-08-06 à 13 05 53" src="https://user-images.githubusercontent.com/19306526/128501815-be3e64af-0604-436a-a08d-41a1a1c0be3f.png">

**Comment by tndrle** [comment]
Release v0.3.0 is out and includes the `\PyLTVerbatimEnv` macro. Thanks for your suggestions and feedback. It will take 2 or 3 days until it is available in TeX Live as well.

Regarding an environment that mimicks the python console: I see that this would be very handy to have. I don't know what it means to implement it, yet. It will take some time to add it. I opened a discussion for it #3.

I close this issue now. Feel free to open a new issue if there are problems with the `\PyLTVerbatimEnv` approach.
